apiVersion: apps/v1
kind: Deployment
metadata:
  name: smstore-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smstore-actions
  template:
    metadata:
      labels:
        app: smstore-actions
    spec:
      containers:
      - image: nguyenducduy/smstore-actions:$SEMAPHORE_WORKFLOW_ID
        name: smstore-actions
        imagePullSecrets: # if using a private image
          - name: dockerhub-user
        env:
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: smstore-hasura-admin-secret
              key: password
        - name: HASURA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: smstore-hasura-jwt-secret
              key: value
        - name: MAILGUN_API_KEY
          valueFrom:
            secretKeyRef:
              name: mailgun-api-key
              key: value
        - name: AES_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: smstore-aes-secret-key
              key: value
        - name: HASURA_GRAPHQL_ENDPOINT
          value: "http://smstore-core/v1/graphql"
        - name: MAILGUN_SENDER
          value: "Kích hoạt tài khoản - Tiệm của tui<mailgun@{}>"
        - name: MAILGUN_URL
          value: "https://api.mailgun.net/v3/{}/messages"
        - name: MAILGUN_DOMAIN
          value: "mail.tiemcuatui.com"
        
      