apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: smstore-actions-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - tiemcuatui.com
    secretName: wildcard-tiemcuatui-com-tls
  rules:
  - host: tiemcuatui.com
    http:
      paths:
      - path: /actions/(.+)
        backend:
          serviceName: smstore-actions
          servicePort: 80
      
