apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: smstore-actions-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - smstore-actions.tiemcuatui.com
    secretName: tiemcuatui-tls
  rules:
  - host: smstore-actions.tiemcuatui.com
    http:
      paths:
      - backend:
          serviceName: smstore-actions
          servicePort: 80
